version: "2.2"

services:
  db:
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    container_name: db
    image: postgres:latest
    hostname: db
    restart: always
    networks:
      - back-tier
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA= /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - 5432



  main-service:
    restart: always
    container_name: core
    networks:
      - back-tier
    build:
      context: ./core
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    ports:
      - "80:80"
    expose:
      - 80

networks:
  back-tier:
    driver: bridge